---
driver:
  name: vagrant
  synced_folders:
    - ["../", "/tools-root"]

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  # puppet_debug: true
  # puppet_verbose: true
  # puppet_logdest:
  #   - console
  #   - /puppet.log
  custom_facts:
    instrumentald_version: <%= `ruby -r#{__FILE__}/../../lib/instrumentald/version -e 'puts Instrumentald::VERSION'`.strip %>
    instrumentald_use_local: true

platforms:
  - name: nocm_ubuntu-12.04
    driver_plugin: vagrant
    driver_config:
      box: nocm_ubuntu-12.04
      box_url: https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-12.04-64-nocm/versions/1.0.1/providers/virtualbox.box
  - name: nocm_ubuntu-16.04
    driver_plugin: vagrant
    driver_config:
      box: nocm_ubuntu-16.04
      box_url: https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-16.04-64-nocm/versions/1.0.0/providers/virtualbox.box
  - name: nocm_centos-6.6
    driver_plugin: vagrant
    driver_config:
      box: nocm_centos-6.6
      box_url: https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.6-64-nocm/versions/1.0.1/providers/virtualbox.box

suites:
  - name: default
    manifest: site.pp
