# Replace YOUR_API_KEY with the API key for your Instrumental project and
# remove the # from the beginning of the following line to have instrumentald
# start sending metrics to your account.

api_key = "YOUR_API_KEY"
# redis = ["tcp://localhost:6379"]
# memcached = ["localhost:11211"]
