#!/bin/sh
set -e
cd "$(dirname "$0")/.."

brew list gnu-tar >/dev/null 2>&1 || brew install gnu-tar
brew list rpm >/dev/null 2>&1 || brew install rpm
brew list go >/dev/null 2>&1 || brew install go --with-cc-all

rbenv which ruby >/dev/null 2>&1 || (brew upgrade ruby-build || true; rbenv install)
gem list -i bundler >/dev/null || gem install bundler
bundle install
