---
driver:
  name: vagrant
  synced_folders:
    - ["../", "/tools-root"]
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  chef_omnibus_url: "https://raw.githubusercontent.com/instrumental/instrumentald/master/chef/omnibus.sh"

platforms:
  - name: ubuntu-12.04
  - name: centos-7.1
  #- name: "d11wtq/gentoo"
  #- name: "opentable/win-2012r2-standard-amd64-nocm"

suites:
  - name: default
    run_list: ["instrumentald"]
    attributes:
      instrumental:
        use_local: true
        local_path: "/tools-root/"
