---
driver:
  name: vagrant
  synced_folders:
    - ["../", "/tools-root"]
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  chef_omnibus_url: "https://raw.githubusercontent.com/instrumental/instrumentald/master/chef/omnibus.sh"

platforms:
  - name: debian-7.11
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  # ubuntu 16 works differently, and this doesn't work currently
  # - name: ubuntu-16.04
  - name: centos-6.7
  # gentoo is probably not a good choice for servers, and would take some more effort to make work
  # - name: "d11wtq/gentoo"

suites:
  - name: default
    run_list: ["instrumentald"]
    attributes:
      instrumental:
        use_local: true
        local_path: "/tools-root/"
