---
driver:
  name: vagrant
  synced_folders:
    - ["../", "/tools-root"]
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.19.36 # pinned to avoid bugs in sc-mongodb, next version of that should fix them

platforms:
  - name: debian-7.11
  - name: debian-8.7
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[instrumentald]
      - recipe[sc-mongodb]
    attributes:
      instrumental:
        use_local: true
        local_path: "/tools-root/"
